endpoints:
  - name: Cloud Jira
    group: atlassian
    url: "https://effectivesoft.atlassian.net/jira"
    interval: 60s
    conditions:
      - "[STATUS] == 200"

  - name: Cloud Wiki
    group: atlassian
    url: "https://effectivesoft.atlassian.net/wiki"
    interval: 60s
    conditions:
      - "[STATUS] == 200"

  - name: monitoring
    group: internal
    url: "https://zabbix.effective-soft.com/zabbix/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: Effective-soft BY website
    group: internal
    url: "https://www.effectivesoft.by/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 120h"

  - name: Effective-soft PL website
    group: internal
    url: "https://www.effectivesoft.pl/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 120h"

 - name: Google website
    group: internal
    url: "https://www.google.com/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 120h"

  - name: Effective-soft COM website
    group: internal
    url: "https://www.effectivesoft.com/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 120h"

  - name: example-dns-query
    url: "8.8.8.8" # Address of the DNS server to use
    interval: 5m
    dns:
      query-name: "example.com"
      query-type: "A"
    conditions:
      - "[BODY] == 93.184.215.14"
      - "[DNS_RCODE] == NOERROR"

  - name: icmp-ping
    url: "icmp://example.org"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: check-domain-expiration
    url: "https://example.org/"
    interval: 1h
    conditions:
      - "[DOMAIN_EXPIRATION] > 720h"

