alerting:
  telegram:
    token: "7345309315:AAHUO-ORb0Uv7DFI2pZGRRPYfV5npNZBqss"
    chat-id: "-1002237411116"

endpoints:
  - name: Atlassian Jira Software Status
    url: "https://jira-software.status.atlassian.com/"
    interval: 60s
    headers:
     Cache-Control: "no-cache"
    conditions:
      - "[BODY] = 'All Systems Operational'"
    alerts:
      - type: telegram
        send-on-resolved: true

  - name: Atlassian Cloud Confluence
    url: "https://status.atlassian.com/products/confluence"
    interval: 60s
    headers:
     Cache-Control: "no-cache"
    conditions:
      - "[BODY].status.description == 'All Systems Operational'"
    alerts:
      - type: telegram
        send-on-resolved: true

  - name: monitoring
    group: internal
    url: "https://zabbix.effective-soft.com/zabbix/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram
        send-on-resolved: true

  - name: Effective-soft BY website
    group: internal
    url: "https://www.effectivesoft.by/"
    interval: 5m
    headers:
     Cache-Control: "no-cache"
    conditions:
      - "[STATUS] == 200"
      - "[TLS_VALID] == true"
    alerts:
      - type: telegram
        send-on-resolved: true

  - name: Effective-soft PL website
    group: internal
    url: "https://www.effectivesoft.pl/"
    interval: 5m
    headers:
     Cache-Control: "no-cache"
    conditions:
      - "[STATUS] == 200"
      - "[TLS_VALID] == true"
    alerts:
      - type: telegram
        send-on-resolved: true

  - name: Google website
    group: internal
    url: "https://www.google.com/"
    interval: 1m
    headers:
     Cache-Control: "no-cache"
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 120h"
    alerts:
      - type: telegram
        send-on-resolved: true

  - name: Effective-soft COM website
    group: internal
    url: "https://www.effectivesoft.com/"
    interval: 5m
    headers:
     Cache-Control: "no-cache"
    conditions:
      - "[STATUS] == 200"
      - "[TLS_VALID] == true"
    alerts:
      - type: telegram
        send-on-resolved: true

